name: flutteractixapp
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  go_router: ^14.2.3
  equatable: ^2.0.5
  http: ^1.2.2
  bloc: ^8.1.4
  meta: ^1.15.0
  dartz: ^0.10.1
  flutter_bloc: ^8.1.6
  qr_flutter: ^4.1.0
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^9.2.2
  flutter_localizations:
    sdk: flutter
  intl: any
  universal_io: ^2.2.2
  http_interceptor: ^2.0.0
  get_it: ^7.7.0
  logger: ^2.4.0
  formz: ^0.7.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - .env
    - assets/images/actix-logo.png
    - assets/images/flutter-logo.png
    - assets/images/github-logo.png
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic

        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 600

        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 700

        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 900
